
export const CATEGORY_MAP = {
  
    gundem: {
        tr: "gundem",
        en: "agenda",
        label_tr: "Gündem",
        label_en: "Agenda",
        showInSidebar: false,
        city: false,
        color: "#2563EB",
    },
 bilim_teknoloji: {
        tr: "bilim-teknoloji",
        en: "science-technology",
        label_tr: "Bilim & Teknoloji",
        label_en: "Science&Tech",
        showInSidebar: false,
        city: false,
        color: "#3B82F6",
    },
    spor: {
        tr: "spor",
        en: "sports",
        label_tr: "Spor",
        label_en: "Sports",
        showInSidebar: true,
        city: false,
        color: "#16A34A",
    },

    magazin: {
        tr: "magazin",
        en: "entertainment",
        label_tr: "Magazin",
        label_en: "Entertainment",
        showInSidebar: false,
        city: false,
        color: "#DB2777",
    },

    ekonomi: {
        tr: "ekonomi",
        en: "economy",
        label_tr: "Ekonomi",
        label_en: "Economy",
        showInSidebar: true,
        city: false,
        color: "#F59E0B",
    },

    finans: {
        tr: "finans",
        en: "finance",
        label_tr: "Finans",
        label_en: "Finance",
        showInSidebar: false,
        city: false,
        color: "#0F766E",
    },

    politika: {
        tr: "politika",
        en: "politics",
        label_tr: "Politika",
        label_en: "Politics",
        showInSidebar: true,
        city: false,
        color: "#7C3AED",
    },

    asayis: {
        tr: "asayis",
        en: "crime",
        label_tr: "Asayiş",
        label_en: "Crime",
        showInSidebar: true,
        city: false,
        color: "#DC2626",
    },

    saglik: {
        tr: "saglik",
        en: "health",
        label_tr: "Sağlık",
        label_en: "Health",
        showInSidebar: true,
        city: false,
        color: "#059669",
    },

    cevre: {
        tr: "cevre",
        en: "environment",
        label_tr: "Çevre",
        label_en: "Environment",
        showInSidebar: true,
        city: false,
        color: "#22C55E",
    },

    genel: {
        tr: "genel",
        en: "general",
        label_tr: "Genel",
        label_en: "General",
        showInSidebar: false,
        city: false,
        color: "#64748B",
    },

    bilim: {
        tr: "bilim",
        en: "science",
        label_tr: "Bilim",
        label_en: "Science",
        showInSidebar: false,
        city: false,
        color: "#0EA5E9",
    },

    /* =======================
        HABER TÜRLERİ
    ======================= */

    ulusal: {
        tr: "ulusal",
        en: "national",
        label_tr: "Ulusal Haber",
        label_en: "National News",
        showInSidebar: false,
        city: false,
        color: "#1D4ED8",
    },

    yerel: {
        tr: "yerel",
        en: "local",
        label_tr: "Yerel Haber",
        label_en: "Local News",
        showInSidebar: false,
        city: false,
        color: "#F97316",
    },

    dis_haber: {
        tr: "dis-haber",
        en: "world",
        label_tr: "Dış Haber",
        label_en: "World News",
        showInSidebar: false,
        city: false,
        color: "#06B6D4",
    },

    haberde_insan: {
        tr: "haberde-insan",
        en: "human-stories",
        label_tr: "Haberde İnsan",
        label_en: "Human Stories",
        showInSidebar: false,
        city: false,
        color: "#E11D48",
    },

    teknoloji: {
        tr: "teknoloji",
        en: "tech",
        label_tr: "Teknoloji",
        label_en: "tech",
        showInSidebar: false,
        city: false,
        color: "#A855F7",
    },


    
 istanbul: {
        tr: "istanbul",
        en: "istanbul",
        label_tr: "İstanbul",
        label_en: "Istanbul",
        showInSidebar: false,
        city: true,
        color: "#820F0F",
    },
 ankara: {
        tr: "ankara",
        en: "ankara",
        label_tr: "Ankara",
        label_en: "Ankara",
        showInSidebar: false,
        city: true,
        color: "#650707",
    },
    izmir: {
        tr: "izmir",
        en: "izmir",
        label_tr: "İzmir",
        label_en: "Izmir",
        showInSidebar: false,
        city: true,
        color: "#670707",
    },

    antalya: {
        tr: "antalya",
        en: "antalya",
        label_tr: "Antalya",
        label_en: "Antalya",
        showInSidebar: false,
        city: true,
        color: "#8E1515",
    }, karabuk: {
        tr: "karabuk",
        en: "karabuk",
        label_tr: "Karabük",
        label_en: "Karabuk",
        showInSidebar: false,
        city: true,
        color: "#7C0D0D",
    },bursa: {
        tr: "bursa",
        en: "bursa",
        label_tr: "Bursa",
        label_en: "Bursa",
        showInSidebar: false,
        city: true,
        color: "#670808",
    },
     kayseri: {
        tr: "kayseri",
        en: "kayseri",
        label_tr: "Kayseri",
        label_en: "Kayseri",
        showInSidebar: false,
        city: true,
        color: "#861111",
    }, trabzon: {
        tr: "trabzon",
        en: "trabzon",
        label_tr: "Trabzon",
        label_en: "Trabzon",
        showInSidebar: false,
        city: true,
        color: "#7C0D0D",
    },
    adana: {
        tr: "adana",
        en: "adana",
        label_tr: "Adana",
        label_en: "Adana",
        showInSidebar: false,
        city: true,
        color: "#7A0B0B",
    },
    adiyaman: {
        tr: "adiyaman",
        en: "adiyaman",
        label_tr: "Adıyaman",
        label_en: "Adiyaman",
        showInSidebar: false,
        city: true,
        color: "#8A1111",
    },
    afyonkarahisar: {
        tr: "afyonkarahisar",
        en: "afyonkarahisar",
        label_tr: "Afyonkarahisar",
        label_en: "Afyonkarahisar",
        showInSidebar: false,
        city: true,
        color: "#6E0A0A",
    },
    agri: {
        tr: "agri",
        en: "agri",
        label_tr: "Ağrı",
        label_en: "Agri",
        showInSidebar: false,
        city: true,
        color: "#8C1414",
    },
    aksaray: {
        tr: "aksaray",
        en: "aksaray",
        label_tr: "Aksaray",
        label_en: "Aksaray",
        showInSidebar: false,
        city: true,
        color: "#730C0C",
    },
    amasya: {
        tr: "amasya",
        en: "amasya",
        label_tr: "Amasya",
        label_en: "Amasya",
        showInSidebar: false,
        city: true,
        color: "#831010",
    },

    ardahan: {
        tr: "ardahan",
        en: "ardahan",
        label_tr: "Ardahan",
        label_en: "Ardahan",
        showInSidebar: false,
        city: true,
        color: "#7C0D0D",
    },
    artvin: {
        tr: "artvin",
        en: "artvin",
        label_tr: "Artvin",
        label_en: "Artvin",
        showInSidebar: false,
        city: true,
        color: "#6A0909",
    },
    aydin: {
        tr: "aydin",
        en: "aydin",
        label_tr: "Aydın",
        label_en: "Aydin",
        showInSidebar: false,
        city: true,
        color: "#901616",
    },
    balikesir: {
        tr: "balikesir",
        en: "balikesir",
        label_tr: "Balıkesir",
        label_en: "Balikesir",
        showInSidebar: false,
        city: true,
        color: "#7F0E0E",
    },
    bartin: {
        tr: "bartin",
        en: "bartin",
        label_tr: "Bartın",
        label_en: "Bartin",
        showInSidebar: false,
        city: true,
        color: "#680808",
    },
    batman: {
        tr: "batman",
        en: "batman",
        label_tr: "Batman",
        label_en: "Batman",
        showInSidebar: false,
        city: true,
        color: "#921818",
    },
    bayburt: {
        tr: "bayburt",
        en: "bayburt",
        label_tr: "Bayburt",
        label_en: "Bayburt",
        showInSidebar: false,
        city: true,
        color: "#760B0B",
    },
    bilecik: {
        tr: "bilecik",
        en: "bilecik",
        label_tr: "Bilecik",
        label_en: "Bilecik",
        showInSidebar: false,
        city: true,
        color: "#8B1212",
    },
    bingol: {
        tr: "bingol",
        en: "bingol",
        label_tr: "Bingöl",
        label_en: "Bingol",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    bitlis: {
        tr: "bitlis",
        en: "bitlis",
        label_tr: "Bitlis",
        label_en: "Bitlis",
        showInSidebar: false,
        city: true,
        color: "#8F1616",
    },
    bolu: {
        tr: "bolu",
        en: "bolu",
        label_tr: "Bolu",
        label_en: "Bolu",
        showInSidebar: false,
        city: true,
        color: "#740B0B",
    },
    burdur: {
        tr: "burdur",
        en: "burdur",
        label_tr: "Burdur",
        label_en: "Burdur",
        showInSidebar: false,
        city: true,
        color: "#830F0F",
    },
   
    canakkale: {
        tr: "canakkale",
        en: "canakkale",
        label_tr: "Çanakkale",
        label_en: "Canakkale",
        showInSidebar: false,
        city: true,
        color: "#951A1A",
    },
    cankiri: {
        tr: "cankiri",
        en: "cankiri",
        label_tr: "Çankırı",
        label_en: "Cankiri",
        showInSidebar: false,
        city: true,
        color: "#7D0D0D",
    },
    corum: {
        tr: "corum",
        en: "corum",
        label_tr: "Çorum",
        label_en: "Corum",
        showInSidebar: false,
        city: true,
        color: "#6C0909",
    },
    denizli: {
        tr: "denizli",
        en: "denizli",
        label_tr: "Denizli",
        label_en: "Denizli",
        showInSidebar: false,
        city: true,
        color: "#8D1414",
    },
    diyarbakir: {
        tr: "diyarbakir",
        en: "diyarbakir",
        label_tr: "Diyarbakır",
        label_en: "Diyarbakir",
        showInSidebar: false,
        city: true,
        color: "#7A0C0C",
    },
    duzce: {
        tr: "duzce",
        en: "duzce",
        label_tr: "Düzce",
        label_en: "Duzce",
        showInSidebar: false,
        city: true,
        color: "#660707",
    },
    edirne: {
        tr: "edirne",
        en: "edirne",
        label_tr: "Edirne",
        label_en: "Edirne",
        showInSidebar: false,
        city: true,
        color: "#901717",
    },
    elazig: {
        tr: "elazig",
        en: "elazig",
        label_tr: "Elazığ",
        label_en: "Elazig",
        showInSidebar: false,
        city: true,
        color: "#770B0B",
    },
    erzincan: {
        tr: "erzincan",
        en: "erzincan",
        label_tr: "Erzincan",
        label_en: "Erzincan",
        showInSidebar: false,
        city: true,
        color: "#881212",
    },
    erzurum: {
        tr: "erzurum",
        en: "erzurum",
        label_tr: "Erzurum",
        label_en: "Erzurum",
        showInSidebar: false,
        city: true,
        color: "#6F0A0A",
    },
    eskisehir: {
        tr: "eskisehir",
        en: "eskisehir",
        label_tr: "Eskişehir",
        label_en: "Eskisehir",
        showInSidebar: false,
        city: true,
        color: "#8E1515",
    },
    gaziantep: {
        tr: "gaziantep",
        en: "gaziantep",
        label_tr: "Gaziantep",
        label_en: "Gaziantep",
        showInSidebar: false,
        city: true,
        color: "#7B0D0D",
    },
    giresun: {
        tr: "giresun",
        en: "giresun",
        label_tr: "Giresun",
        label_en: "Giresun",
        showInSidebar: false,
        city: true,
        color: "#680808",
    },
    gumushane: {
        tr: "gumushane",
        en: "gumushane",
        label_tr: "Gümüşhane",
        label_en: "Gumushane",
        showInSidebar: false,
        city: true,
        color: "#951A1A",
    },
    hakkari: {
        tr: "hakkari",
        en: "hakkari",
        label_tr: "Hakkâri",
        label_en: "Hakkari",
        showInSidebar: false,
        city: true,
        color: "#7E0E0E",
    },
    hatay: {
        tr: "hatay",
        en: "hatay",
        label_tr: "Hatay",
        label_en: "Hatay",
        showInSidebar: false,
        city: true,
        color: "#6A0909",
    },
    igdir: {
        tr: "igdir",
        en: "igdir",
        label_tr: "Iğdır",
        label_en: "Igdir",
        showInSidebar: false,
        city: true,
        color: "#8F1616",
    },
    isparta: {
        tr: "isparta",
        en: "isparta",
        label_tr: "Isparta",
        label_en: "Isparta",
        showInSidebar: false,
        city: true,
        color: "#750B0B",
    },
    
    kahramanmaras: {
        tr: "kahramanmaras",
        en: "kahramanmaras",
        label_tr: "Kahramanmaraş",
        label_en: "Kahramanmaras",
        showInSidebar: false,
        city: true,
        color: "#931818",
    },
    
    karaman: {
        tr: "karaman",
        en: "karaman",
        label_tr: "Karaman",
        label_en: "Karaman",
        showInSidebar: false,
        city: true,
        color: "#6D0909",
    },
    kars: {
        tr: "kars",
        en: "kars",
        label_tr: "Kars",
        label_en: "Kars",
        showInSidebar: false,
        city: true,
        color: "#8C1414",
    },
    kastamonu: {
        tr: "kastamonu",
        en: "kastamonu",
        label_tr: "Kastamonu",
        label_en: "Kastamonu",
        showInSidebar: false,
        city: true,
        color: "#780B0B",
    },

    kilis: {
        tr: "kilis",
        en: "kilis",
        label_tr: "Kilis",
        label_en: "Kilis",
        showInSidebar: false,
        city: true,
        color: "#6B0808",
    },
    kirikkale: {
        tr: "kirikkale",
        en: "kirikkale",
        label_tr: "Kırıkkale",
        label_en: "Kirikkale",
        showInSidebar: false,
        city: true,
        color: "#971C1C",
    },
    kirklareli: {
        tr: "kirklareli",
        en: "kirklareli",
        label_tr: "Kırklareli",
        label_en: "Kirklareli",
        showInSidebar: false,
        city: true,
        color: "#7D0D0D",
    },
    kirsehir: {
        tr: "kirsehir",
        en: "kirsehir",
        label_tr: "Kırşehir",
        label_en: "Kirsehir",
        showInSidebar: false,
        city: true,
        color: "#6C0909",
    },
    kocaeli: {
        tr: "kocaeli",
        en: "kocaeli",
        label_tr: "Kocaeli",
        label_en: "Kocaeli",
        showInSidebar: false,
        city: true,
        color: "#8E1515",
    },
    konya: {
        tr: "konya",
        en: "konya",
        label_tr: "Konya",
        label_en: "Konya",
        showInSidebar: false,
        city: true,
        color: "#790B0B",
    },
    kutahya: {
        tr: "kutahya",
        en: "kutahya",
        label_tr: "Kütahya",
        label_en: "Kutahya",
        showInSidebar: false,
        city: true,
        color: "#861212",
    },
    malatya: {
        tr: "malatya",
        en: "malatya",
        label_tr: "Malatya",
        label_en: "Malatya",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    manisa: {
        tr: "manisa",
        en: "manisa",
        label_tr: "Manisa",
        label_en: "Manisa",
        showInSidebar: false,
        city: true,
        color: "#911717",
    },
    mardin: {
        tr: "mardin",
        en: "mardin",
        label_tr: "Mardin",
        label_en: "Mardin",
        showInSidebar: false,
        city: true,
        color: "#7E0E0E",
    },
    mersin: {
        tr: "mersin",
        en: "mersin",
        label_tr: "Mersin",
        label_en: "Mersin",
        showInSidebar: false,
        city: true,
        color: "#6A0909",
    },
    mugla: {
        tr: "mugla",
        en: "mugla",
        label_tr: "Muğla",
        label_en: "Mugla",
        showInSidebar: false,
        city: true,
        color: "#8F1616",
    },
    mus: {
        tr: "mus",
        en: "mus",
        label_tr: "Muş",
        label_en: "Mus",
        showInSidebar: false,
        city: true,
        color: "#740B0B",
    },
    nevsehir: {
        tr: "nevsehir",
        en: "nevsehir",
        label_tr: "Nevşehir",
        label_en: "Nevsehir",
        showInSidebar: false,
        city: true,
        color: "#861212",
    },
    nigde: {
        tr: "nigde",
        en: "nigde",
        label_tr: "Niğde",
        label_en: "Nigde",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    ordu: {
        tr: "ordu",
        en: "ordu",
        label_tr: "Ordu",
        label_en: "Ordu",
        showInSidebar: false,
        city: true,
        color: "#901717",
    },
    osmaniye: {
        tr: "osmaniye",
        en: "osmaniye",
        label_tr: "Osmaniye",
        label_en: "Osmaniye",
        showInSidebar: false,
        city: true,
        color: "#7C0D0D",
    },
    rize: {
        tr: "rize",
        en: "rize",
        label_tr: "Rize",
        label_en: "Rize",
        showInSidebar: false,
        city: true,
        color: "#6A0909",
    },
    sakarya: {
        tr: "sakarya",
        en: "sakarya",
        label_tr: "Sakarya",
        label_en: "Sakarya",
        showInSidebar: false,
        city: true,
        color: "#8E1515",
    },
    samsun: {
        tr: "samsun",
        en: "samsun",
        label_tr: "Samsun",
        label_en: "Samsun",
        showInSidebar: false,
        city: true,
        color: "#780B0B",
    },
    sanliurfa: {
        tr: "sanliurfa",
        en: "sanliurfa",
        label_tr: "Şanlıurfa",
        label_en: "Sanliurfa",
        showInSidebar: false,
        city: true,
        color: "#871212",
    },
    siirt: {
        tr: "siirt",
        en: "siirt",
        label_tr: "Siirt",
        label_en: "Siirt",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    sinop: {
        tr: "sinop",
        en: "sinop",
        label_tr: "Sinop",
        label_en: "Sinop",
        showInSidebar: false,
        city: true,
        color: "#8F1616",
    },
    sivas: {
        tr: "sivas",
        en: "sivas",
        label_tr: "Sivas",
        label_en: "Sivas",
        showInSidebar: false,
        city: true,
        color: "#740B0B",
    },
    sirnak: {
        tr: "sirnak",
        en: "sirnak",
        label_tr: "Şırnak",
        label_en: "Sirnak",
        showInSidebar: false,
        city: true,
        color: "#861212",
    },
    tekirdag: {
        tr: "tekirdag",
        en: "tekirdag",
        label_tr: "Tekirdağ",
        label_en: "Tekirdag",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    tokat: {
        tr: "tokat",
        en: "tokat",
        label_tr: "Tokat",
        label_en: "Tokat",
        showInSidebar: false,
        city: true,
        color: "#901717",
    },
   
    tunceli: {
        tr: "tunceli",
        en: "tunceli",
        label_tr: "Tunceli",
        label_en: "Tunceli",
        showInSidebar: false,
        city: true,
        color: "#6A0909",
    },
    usak: {
        tr: "usak",
        en: "usak",
        label_tr: "Uşak",
        label_en: "Usak",
        showInSidebar: false,
        city: true,
        color: "#8E1515",
    },
    van: {
        tr: "van",
        en: "van",
        label_tr: "Van",
        label_en: "Van",
        showInSidebar: false,
        city: true,
        color: "#780B0B",
    },
    yalova: {
        tr: "yalova",
        en: "yalova",
        label_tr: "Yalova",
        label_en: "Yalova",
        showInSidebar: false,
        city: true,
        color: "#871212",
    },
    yozgat: {
        tr: "yozgat",
        en: "yozgat",
        label_tr: "Yozgat",
        label_en: "Yozgat",
        showInSidebar: false,
        city: true,
        color: "#6B0909",
    },
    zonguldak: {
        tr: "zonguldak",
        en: "zonguldak",
        label_tr: "Zonguldak",
        label_en: "Zonguldak",
        showInSidebar: false,
        city: true,
        color: "#8F1616",
    }
    , londra: {
    tr: "londra",
    en: "london",
    label_tr: "Londra",
    label_en: "London",
    showInSidebar: false,
    city: true,
    global: true,
    color: "#6B0909",
  },
  berlin: {
    tr: "berlin",
    en: "berlin",
    label_tr: "Berlin",
    label_en: "BERLIN",
    showInSidebar: false,
    city: true,
    global: true,
    color: "#8F1616",
  }


} as const;




export type CategoryKey = keyof typeof CATEGORY_MAP;



/**
 * CATEGORY_MAP
 * ------------------------------------------------------------------
 * Bu dosya, sitede kullanılan TÜM kategori ve şehir tanımlarının
 * TEK ve MERKEZİ kaynağıdır.
 *
 * Amaç:
 * - Kategori / şehir bilgilerini hard-code etmek yerine
 *   tek bir yerden yönetmek
 * - URL yapısı, navigasyon, dil desteği ve görsel ayarları
 *   tutarlı hale getirmek
 *
 * İçerdiği bilgiler:
 * - tr / en        → URL slug’ları (çok dilli routing için)
 * - label_tr / en → Kullanıcıya gösterilen başlıklar
 * - showInSidebar → Üst menüde (Topbar) görünüp görünmeyeceği
 * - city          → Şehir kategorisi mi? (Cities menüsü için)
 * - global        → Global (EN) şehirlerde gösterilsin mi
 * - color         → Kategoriye özel renk (etiket, badge, UI)
 *
 * Nerelerde kullanılıyor?
 * ------------------------------------------------------------------
 * 1️⃣ Navigation / Topbar
 *    - Sidebar kategorilerini filtrelemek
 *    - Cities menüsünü oluşturmak
 *    - Aktif kategori kontrolü yapmak
 *
 * 2️⃣ Routing & URL çözümleme
 *    - /spor, /en/sports gibi URL’lerden
 *      doğru CategoryKey’i bulmak
 *
 * 3️⃣ Sayfa başlıkları
 *    - Kategori sayfalarında doğru label_tr / label_en göstermek
 *
 * 4️⃣ Type safety (TypeScript)
 *    - CategoryKey tipi sayesinde
 *      yanlış kategori kullanımını compile-time’da yakalamak
 *
 * Önemli Notlar:
 * ------------------------------------------------------------------
 * - `as const` kullanıldığı için tüm değerler IMMUTABLE’dır
 * - Yeni bir kategori veya şehir eklemek için
 *   SADECE bu dosyayı güncellemek yeterlidir
 * - Başka hiçbir yerde string kategori adı yazılmamalıdır
 */
