export type CityItem = {
  slug: string;
  labelTR: string;
  apiName: string;     // geocoding name
  country: string;     // geocoding country filter (name or code)
  admin1?: string;     // optional (province/state) for better match
};

export const CITIES: CityItem[] = [
  // --- Türkiye 81 il ---
  { slug: "adana", labelTR: "Adana", apiName: "Adana", country: "Turkey" },
  { slug: "adiyaman", labelTR: "Adıyaman", apiName: "Adiyaman", country: "Turkey" },
  { slug: "afyonkarahisar", labelTR: "Afyonkarahisar", apiName: "Afyonkarahisar", country: "Turkey" },
  { slug: "agri", labelTR: "Ağrı", apiName: "Agri", country: "Turkey" },
  { slug: "aksaray", labelTR: "Aksaray", apiName: "Aksaray", country: "Turkey" },
  { slug: "amasya", labelTR: "Amasya", apiName: "Amasya", country: "Turkey" },
  { slug: "ankara", labelTR: "Ankara", apiName: "Ankara", country: "Turkey" },
  { slug: "antalya", labelTR: "Antalya", apiName: "Antalya", country: "Turkey" },
  { slug: "ardahan", labelTR: "Ardahan", apiName: "Ardahan", country: "Turkey" },
  { slug: "artvin", labelTR: "Artvin", apiName: "Artvin", country: "Turkey" },
  { slug: "aydin", labelTR: "Aydın", apiName: "Aydin", country: "Turkey" },
  { slug: "balikesir", labelTR: "Balıkesir", apiName: "Balikesir", country: "Turkey" },
  { slug: "bartin", labelTR: "Bartın", apiName: "Bartin", country: "Turkey" },
  { slug: "batman", labelTR: "Batman", apiName: "Batman", country: "Turkey" },
  { slug: "bayburt", labelTR: "Bayburt", apiName: "Bayburt", country: "Turkey" },
  { slug: "bilecik", labelTR: "Bilecik", apiName: "Bilecik", country: "Turkey" },
  { slug: "bingol", labelTR: "Bingöl", apiName: "Bingol", country: "Turkey" },
  { slug: "bitlis", labelTR: "Bitlis", apiName: "Bitlis", country: "Turkey" },
  { slug: "bolu", labelTR: "Bolu", apiName: "Bolu", country: "Turkey" },
  { slug: "burdur", labelTR: "Burdur", apiName: "Burdur", country: "Turkey" },
  { slug: "bursa", labelTR: "Bursa", apiName: "Bursa", country: "Turkey" },
  { slug: "canakkale", labelTR: "Çanakkale", apiName: "Canakkale", country: "Turkey" },
  { slug: "cankiri", labelTR: "Çankırı", apiName: "Cankiri", country: "Turkey" },
  { slug: "corum", labelTR: "Çorum", apiName: "Corum", country: "Turkey" },
  { slug: "denizli", labelTR: "Denizli", apiName: "Denizli", country: "Turkey" },
  { slug: "diyarbakir", labelTR: "Diyarbakır", apiName: "Diyarbakir", country: "Turkey" },
  { slug: "duzce", labelTR: "Düzce", apiName: "Duzce", country: "Turkey" },
  { slug: "edirne", labelTR: "Edirne", apiName: "Edirne", country: "Turkey" },
  { slug: "elazig", labelTR: "Elazığ", apiName: "Elazıg", country: "Turkey" },
  { slug: "erzincan", labelTR: "Erzincan", apiName: "Erzincan", country: "Turkey" },
  { slug: "erzurum", labelTR: "Erzurum", apiName: "Erzurum", country: "Turkey" },
  { slug: "eskisehir", labelTR: "Eskişehir", apiName: "Eskisehir", country: "Turkey" },
  { slug: "gaziantep", labelTR: "Gaziantep", apiName: "Gaziantep", country: "Turkey" },
  { slug: "giresun", labelTR: "Giresun", apiName: "Giresun", country: "Turkey" },
  { slug: "gumushane", labelTR: "Gümüşhane", apiName: "Gumushane", country: "Turkey" },
  { slug: "hakkari", labelTR: "Hakkâri", apiName: "Hakkari", country: "Turkey" },
  { slug: "hatay", labelTR: "Hatay", apiName: "Hatay", country: "Turkey" },
  { slug: "igdir", labelTR: "Iğdır", apiName: "Igdir", country: "Turkey" },
  { slug: "isparta", labelTR: "Isparta", apiName: "Isparta", country: "Turkey" },
  { slug: "istanbul", labelTR: "İstanbul", apiName: "Istanbul", country: "Turkey" },
  { slug: "izmir", labelTR: "İzmir", apiName: "Izmir", country: "Turkey" },
  { slug: "kahramanmaras", labelTR: "Kahramanmaraş", apiName: "Kahramanmaras", country: "Turkey" },
  { slug: "karabuk", labelTR: "Karabük", apiName: "Karabuk", country: "Turkey" },
  { slug: "karaman", labelTR: "Karaman", apiName: "Karaman", country: "Turkey" },
  { slug: "kars", labelTR: "Kars", apiName: "Kars", country: "Turkey" },
  { slug: "kastamonu", labelTR: "Kastamonu", apiName: "Kastamonu", country: "Turkey" },
  { slug: "kayseri", labelTR: "Kayseri", apiName: "Kayseri", country: "Turkey" },
  { slug: "kirikkale", labelTR: "Kırıkkale", apiName: "Kırıkkale", country: "Turkey" },
  { slug: "kirklareli", labelTR: "Kırklareli", apiName: "Kırklareli", country: "Turkey" },
  { slug: "kirsehir", labelTR: "Kırşehir", apiName: "kırsehir", country: "Turkey" },
  { slug: "kocaeli", labelTR: "Kocaeli", apiName: "Kocaeli", country: "Turkey" },
  { slug: "konya", labelTR: "Konya", apiName: "Konya", country: "Turkey" },
  { slug: "kutahya", labelTR: "Kütahya", apiName: "Kutahya", country: "Turkey" },
  { slug: "malatya", labelTR: "Malatya", apiName: "Malatya", country: "Turkey" },
  { slug: "manisa", labelTR: "Manisa", apiName: "Manisa", country: "Turkey" },
  { slug: "mardin", labelTR: "Mardin", apiName: "Mardin", country: "Turkey" },
  { slug: "mersin", labelTR: "Mersin", apiName: "Mersin", country: "Turkey" },
  { slug: "mugla", labelTR: "Muğla", apiName: "Mugla", country: "Turkey" },
  { slug: "mus", labelTR: "Muş", apiName: "Mus", country: "Turkey" },
  { slug: "nevsehir", labelTR: "Nevşehir", apiName: "Nevsehir", country: "Turkey" },
  { slug: "nigde", labelTR: "Niğde", apiName: "Nigde", country: "Turkey" },
  { slug: "ordu", labelTR: "Ordu", apiName: "Ordu", country: "Turkey" },
  { slug: "osmaniye", labelTR: "Osmaniye", apiName: "Osmaniye", country: "Turkey" },
  { slug: "rize", labelTR: "Rize", apiName: "Rize", country: "Turkey" },
  { slug: "sakarya", labelTR: "Sakarya", apiName: "Sakarya", country: "Turkey" },
  { slug: "samsun", labelTR: "Samsun", apiName: "Samsun", country: "Turkey" },
  { slug: "sanliurfa", labelTR: "Şanlıurfa", apiName: "Sanliurfa", country: "Turkey" },
  { slug: "siirt", labelTR: "Siirt", apiName: "Siirt", country: "Turkey" },
  { slug: "sinop", labelTR: "Sinop", apiName: "Sinop", country: "Turkey" },
  { slug: "sirnak", labelTR: "Şırnak", apiName: "Sirnak", country: "Turkey" },
  { slug: "sivas", labelTR: "Sivas", apiName: "Sivas", country: "Turkey" },
  { slug: "tekirdag", labelTR: "Tekirdağ", apiName: "Tekirdag", country: "Turkey" },
  { slug: "tokat", labelTR: "Tokat", apiName: "Tokat", country: "Turkey" },
  { slug: "trabzon", labelTR: "Trabzon", apiName: "Trabzon", country: "Turkey" },
  { slug: "tunceli", labelTR: "Tunceli", apiName: "Tunceli", country: "Turkey" },
  { slug: "usak", labelTR: "Uşak", apiName: "Usak", country: "Turkey" },
  { slug: "van", labelTR: "Van", apiName: "Van", country: "Turkey" },
  { slug: "yalova", labelTR: "Yalova", apiName: "Yalova", country: "Turkey" },
  { slug: "yozgat", labelTR: "Yozgat", apiName: "Yozgat", country: "Turkey" },
  { slug: "zonguldak", labelTR: "Zonguldak", apiName: "Zonguldak", country: "Turkey" },

];

export const WORLD_CITIES: CityItem[] = [
  { slug: "london", labelTR: "Londra", apiName: "London", country: "United Kingdom" },
  { slug: "paris", labelTR: "Paris", apiName: "Paris", country: "France" },
  { slug: "berlin", labelTR: "Berlin", apiName: "Berlin", country: "Germany" },
  { slug: "new-york", labelTR: "New York", apiName: "New York", country: "United States" },
  { slug: "dubai", labelTR: "Dubai", apiName: "Dubai", country: "United Arab Emirates" },
  { slug: "riyadh", labelTR: "Riyad", apiName: "Riyadh", country: "Saudi Arabia" },
];

export const ALL_CITIES: CityItem[] = [...CITIES, ...WORLD_CITIES];
